# Generated by Django 4.1.7 on 2023-03-03 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logros", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logro",
            name="foto",
            field=models.ImageField(null=True, upload_to="logros/fotos"),
        ),
    ]
