# Generated by Django 4.1.7 on 2023-03-03 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logros", "0002_alter_logro_foto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logro",
            name="foto",
            field=models.ImageField(null=True, upload_to="fotos"),
        ),
    ]
